[2025-05-27T07:02:17.291+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rate_fetch_dag.insert_exchange_data manual__2025-05-27T07:02:12.745026+00:00 [queued]>
[2025-05-27T07:02:17.294+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rate_fetch_dag.insert_exchange_data manual__2025-05-27T07:02:12.745026+00:00 [queued]>
[2025-05-27T07:02:17.294+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-27T07:02:17.299+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): insert_exchange_data> on 2025-05-27 07:02:12.745026+00:00
[2025-05-27T07:02:17.300+0000] {standard_task_runner.py:60} INFO - Started process 2049 to run task
[2025-05-27T07:02:17.302+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'exchange_rate_fetch_dag', 'insert_exchange_data', 'manual__2025-05-27T07:02:12.745026+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/fetch_exchange_dag.py', '--cfg-path', '/tmp/tmps55d0j7h']
[2025-05-27T07:02:17.303+0000] {standard_task_runner.py:88} INFO - Job 26: Subtask insert_exchange_data
[2025-05-27T07:02:17.318+0000] {task_command.py:423} INFO - Running <TaskInstance: exchange_rate_fetch_dag.insert_exchange_data manual__2025-05-27T07:02:12.745026+00:00 [running]> on host e6eb47a0cbe8
[2025-05-27T07:02:17.344+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exchange_rate_fetch_dag' AIRFLOW_CTX_TASK_ID='insert_exchange_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-27T07:02:12.745026+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-27T07:02:12.745026+00:00'
[2025-05-27T07:02:17.344+0000] {logging_mixin.py:188} INFO - Looking for file: /opt/***/data_2025-05-27.json
[2025-05-27T07:02:17.344+0000] {logging_mixin.py:188} INFO - File exists? True
[2025-05-27T07:02:17.345+0000] {logging_mixin.py:188} INFO - Loaded data keys: dict_keys(['success', 'timestamp', 'base', 'date', 'rates'])
[2025-05-27T07:02:17.346+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/insert_exchange_data.py", line 28, in insert_exchange_data
    cur.execute("""
psycopg2.errors.InvalidColumnReference: there is no unique or exclusion constraint matching the ON CONFLICT specification

[2025-05-27T07:02:17.348+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=exchange_rate_fetch_dag, task_id=insert_exchange_data, execution_date=20250527T070212, start_date=20250527T070217, end_date=20250527T070217
[2025-05-27T07:02:17.354+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 26 for task insert_exchange_data (there is no unique or exclusion constraint matching the ON CONFLICT specification
; 2049)
[2025-05-27T07:02:17.358+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-27T07:02:17.364+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
